"""Post-verdict targeted analyses — EXPLORATORY ONLY (docs/analysis/post-verdict/).

Zero new subject calls: everything is re-analysis of the recorded event store
via the committed close-out adjudicator's loaders. Nothing here is
verdict-bearing; all confirmatory numbers live in docs/phase5-close/.

Outputs (regenerable: cd artifacts/api-server && uv run --with numpy --with
scipy python engine/gen_post_verdict.py):
  1. clause-b-anatomy.md  (+ figure-sources/pv-swap-choice.csv)
  2. p13-deep-dive.md     (+ pv-p13-cells.csv, pv-p13-trajectories.csv)
  3. interior-census.md   (+ pv-interior-census.csv)
  4. p52-decomposition.md
  5. entropy-anomaly.md   (+ pv-entropy-decomposition.csv)
  + INDEX.md
"""
from __future__ import annotations

import csv
import json
import os
import sqlite3
import sys
from collections import defaultdict

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

import phase5_closeout_adjudicate as adj  # noqa: E402

REPO = adj.REPO_ROOT
PV = os.path.join(REPO, "docs", "analysis", "post-verdict")
FS = os.path.join(PV, "figure-sources")
BANNER = ("> **EXPLORATORY — post-verdict re-analysis of recorded data. Not "
          "verdict-bearing; the registered record is closed. Generated by "
          "`engine/gen_post_verdict.py` from the event store; regenerable.**\n")


def wcsv(path, header, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
    print("wrote", os.path.relpath(path, REPO), f"({len(rows)} rows)")


def wmd(name, text):
    os.makedirs(PV, exist_ok=True)
    p = os.path.join(PV, name)
    with open(p, "w") as f:
        f.write(text)
    print("wrote", os.path.relpath(p, REPO))


def ci(k, n):
    lo, hi = adj._cp_bounds(k, n)
    return f"[{lo:.3f}, {hi:.3f}]"


def main() -> int:
    runs = adj.load_runs()
    personas = adj.load_personas()
    col = adj.collect(runs, personas)
    arms = adj.load_p5_arms()
    report = json.load(open(os.path.join(REPO, "docs", "phase5-close",
                                         "adjudication-report.json")))
    pdoc = json.load(open(os.path.join(adj.P5DOCS, "personas-v4.json")))
    pmap = {p["id"]: p for p in pdoc["personas"]}

    # ================================================== 1. clause-(b) anatomy
    rows = []
    for (pid, T), (k, n) in sorted(col["refusal"].items()):
        lo, hi = adj._cp_bounds(k, n)
        rows.append([pid, personas[pid], T, k, n, round(k / n, 4),
                     round(lo, 4), round(hi, 4), n - k,
                     round((n - k) / n, 4)])
    wcsv(os.path.join(FS, "pv-swap-choice.csv"),
         ["personaId", "leaning", "temperature", "refusalK", "seats",
          "refusalShare", "cpLo", "cpHi", "wordChoiceK", "wordChoiceShare"],
         rows)

    t07 = {pid: col["refusal"][(pid, 0.7)] for pid in sorted(personas)}
    tbl = ["| persona | leaning | refusal k/n (T=0.7) | share | CP95 |",
           "|---|---|---|---|---|"]
    for pid, (k, n) in t07.items():
        tbl.append(f"| {pid} | {personas[pid]} | {k}/{n} | {k/n:.3f} "
                   f"| {ci(k, n)} |")
    md = f"""# Clause-(b) confound anatomy — what the swap passes do and do not show

{BANNER}
**What this is:** anatomy of the P5-3 clause-(b) result (all 16 personas
passed via the swap-refusal clause; p13 alone also passed clause (a)).
Confirmatory source: `docs/phase5-close/adjudication-report.json` P5-3.

## The confound, stated plainly

In the swap cell the option displayed under the word COOPERATE is the
payoff-dominant option. "Refuses the dominated option" and "follows the
COOPERATE word" are therefore **the same physical choice**. The sealed
predicate keys on the choice; it cannot distinguish incentive-driven
refusal from lexical word-following. Every clause-(b) pass below carries
this ambiguity.

## Per-persona swap-choice table (T=0.7, seat-level)

{chr(10).join(tbl)}

Sweep personas (p02, p06, p11, p15) also ran at T=1.0/1.3 — full table
incl. those rows: `figure-sources/pv-swap-choice.csv`. Refusal never drops
below CP LB 0.55 anywhere; leaning does not separate the rates.

## What the recorded data can and cannot decide

- **Can:** the *choice-level* claim — personas overwhelmingly take the
  payoff-dominant / COOPERATE-worded option (bare swap twin
  `p4-d2-w1-can-sw-gpt`: 0/40 refusals — the bare subject follows the word
  to the dominated option; every persona reverses that). The direction of
  the persona effect at the choice level is unambiguous.
- **Cannot:** the *mechanism* — whether personas respond to the payoff
  structure or the label. The de-confounding cell (balanced payoffs ×
  persona, where word and dominance dissociate) **was never run** and is
  scope-sealed to future work (`docs/paper/scope-seal.md`).
- **Cross-reference (bare anchor):** Phase 4's bare word-vs-payoff probe
  (P4-D2-3, aligned/balanced coding) found 0 word-driven refusals in both
  models (CP [0.000, 0.088] each; `docs/phase4/d2-report.md`), and Phase 4
  D2 established bare word-following in the swap cell for gpt (word-choice
  mean 0.0 on the role scale = 100% word-side). Personas invert the bare
  subject's swap behavior; which lever they pull remains open.
- The coop-leaning × swap descriptive probe (outcome-blind decision D2)
  shows the same word-side choice for cooperative-leaning personas —
  *consistent with* lexical operation, but not dispositive (word and
  payoff still coincide there).

No spin: 16/16 clause-(b) passes are real, registered, and
mechanism-ambiguous by design of the cell.
"""
    wmd("clause-b-anatomy.md", md)

    # ================================================== 2. p13 deep dive
    p13 = pmap["p13"]
    eps_a = col["epsA"]
    # every p13 cell across the design
    cellrows = []
    for (pid, cell), eps in sorted(eps_a.items()):
        if pid != "p13":
            continue
        g = adj.gate_cell(eps)
        cellrows.append(["tier-A", cell, 0.7, len(eps), g["k"], g["n"],
                         round(g["mean"], 4), round(g["cp95"][0], 4),
                         round(g["cp95"][1], 4), int(g["interior"])])
    for (pid, cell), eps in sorted(col["tierC"].items()):
        if pid == "p13":
            g = adj.gate_cell(eps)
            cellrows.append(["tier-C (gemini)", cell, 0.7, len(eps), g["k"],
                             g["n"], round(g["mean"], 4),
                             round(g["cp95"][0], 4), round(g["cp95"][1], 4),
                             int(g["interior"])])
    wcsv(os.path.join(FS, "pv-p13-cells.csv"),
         ["tier", "cell", "temperature", "episodes", "k", "n",
          "meanRound1Coop", "cpLo", "cpHi", "interior"], cellrows)

    # round-level trajectories for the two interior δ cells (s2a pair)
    traj_cells = ["rep-d10-s2a", "rep-d90-s2a"]
    p13_arms = {aid: a for aid, a in arms.items()
                if a.get("personaId") == "p13" and a["cell"] in traj_cells
                and a["block"].startswith("P5A")}
    rid_arm = {rid: r["armId"] for rid, r in runs.items()
               if r["armId"] in p13_arms and r["completed"]
               and not r["invalid"]}
    per_round = defaultdict(lambda: [0, 0])  # (cell, round) -> [coopSeats, seats]
    db = sqlite3.connect(f"file:{adj.DB_PATH}?mode=ro", uri=True)
    for rid, payload in db.execute(
            "SELECT run_id, payload FROM events WHERE type='round.played'"):
        if rid not in rid_arm:
            continue
        d = json.loads(payload)
        cell = arms[rid_arm[rid]]["cell"]
        c = runs[rid]["coopRole"]
        key = (cell, d["roundNumber"])
        per_round[key][0] += (d["player1Action"] == c) + (d["player2Action"] == c)
        per_round[key][1] += 2
    trows = [[cell, rnd, k, n, round(k / n, 4)]
             for (cell, rnd), (k, n) in sorted(per_round.items())]
    wcsv(os.path.join(FS, "pv-p13-trajectories.csv"),
         ["cell", "round", "coopSeats", "seats", "coopRate"], trows)

    # p13 vs the other 15
    def prof(pid):
        means = {c: sum(eps_a[(pid, c)]) / len(eps_a[(pid, c)])
                 for c in adj.TIER_A_CELLS}
        ints = sum(adj.gate_cell(eps_a[(pid, c)])["interior"]
                   for c in adj.TIER_A_CELLS)
        k, n = col["refusal"][(pid, 0.7)]
        return means, ints, k / n
    others = sorted(p for p in personas if p != "p13")
    p13m, p13i, p13r = prof("p13")
    cmp_tbl = ["| metric | p13 | others: min / median / max |", "|---|---|---|"]
    for c in adj.TIER_A_CELLS:
        vals = sorted(prof(p)[0][c] for p in others)
        cmp_tbl.append(f"| mean r1-coop {c} | {p13m[c]:.3f} | {vals[0]:.3f} / "
                       f"{vals[7]:.3f} / {vals[-1]:.3f} |")
    ivals = sorted(prof(p)[1] for p in others)
    rvals = sorted(prof(p)[2] for p in others)
    cmp_tbl.append(f"| interior tier-A cells | {p13i} | {ivals[0]} / "
                   f"{ivals[7]} / {ivals[-1]} |")
    cmp_tbl.append(f"| swap refusal share (T=0.7) | {p13r:.3f} | "
                   f"{rvals[0]:.3f} / {rvals[7]:.3f} / {rvals[-1]:.3f} |")

    # trait gradient: personas sharing exactly 2 of 3 factors
    f13 = p13["factors"]
    grad = []
    for pid, p in sorted(pmap.items()):
        if pid == "p13":
            continue
        shared = sum(p["factors"][d] == f13[d] for d in ("d1", "d2", "d3"))
        if shared == 2:
            m, i, r = prof(pid)
            diff = [d for d in ("d1", "d2", "d3")
                    if p["factors"][d] != f13[d]][0]
            grad.append((pid, diff, p["factors"][diff], m, i, r))
    gtbl = ["| persona | differs on | value | " +
            " | ".join(adj.TIER_A_CELLS) + " | interior | refusal |",
            "|---" * (len(adj.TIER_A_CELLS) + 5) + "|"]
    gtbl.append("| **p13** | — | — | " +
                " | ".join(f"{p13m[c]:.3f}" for c in adj.TIER_A_CELLS) +
                f" | {p13i} | {p13r:.3f} |")
    for pid, diff, val, m, i, r in grad:
        gtbl.append(f"| {pid} | {diff} | {val} | " +
                    " | ".join(f"{m[c]:.3f}" for c in adj.TIER_A_CELLS) +
                    f" | {i} | {r:.3f} |")
    slope = report["P5-3"]["perPersona"]["p13"]["detail"]["a"]["s2a"]["slope"]
    md = f"""# p13 deep-dive — the program's sole Family-E δ-slope pass

{BANNER}
> **Status update (R2, 2026-07-29):** the slope interpretation is
> **suggestive**, not confirmatory — family permutation p = 0.0525 ±
> 0.0050 over the 32-candidate clause-(a) family
> (`../r2/p13-family-audit.md`). The registered mechanical verdict is
> unchanged. "Pass" below means the registered gate+slope fired.

**What this is:** everything the record holds on p13 (Harper), the only
arm in the entire program to pass the human-signature δ-slope assay
(clause (a), s2a level: one-sided 95% LB = {slope['lowerBound95']:+.3f}).

## Persona card (verbatim, sealed)

- id: `p13` — sha256 `{p13['sha256']}`
- factors: d1=`{f13['d1']}`, d2=`{f13['d2']}`, d3=`{f13['d3']}`
  (ageBand `{f13['ageBand']}`); leaning: {p13['leaning']}
- preamble (byte-exact): "{p13['preamble']}"

## Every p13 cell across the design

`figure-sources/pv-p13-cells.csv` — 6 tier-A cells (gpt, T=0.7) + tier-C
gemini descriptive replicas where run. Corrected census: **4 interior
cells** — rep-d10-s2a, rep-d90-s2a, rep-d90-s2p, os-community; both s2a
δ-levels interior is what armed the clause-(a) slope test.

## Round-level trajectories, interior δ pair (s2a)

`figure-sources/pv-p13-trajectories.csv` — seat-level cooperation by round
for rep-d10-s2a vs rep-d90-s2a. The δ-slope verdict uses round 1 only
(registered convention); the trajectories are exploratory texture.

## p13 vs the other 15

{chr(10).join(cmp_tbl)}

## Trait gradient (EXPLORATORY — 5 personas share 2 of 3 factors, n=1 per point; no inferential weight)

{chr(10).join(gtbl)}

Reading: no 2-of-3 neighbor reproduces p13's pattern; the
competitive+patient+risk-averse conjunction (not any pair) is where the
δ-response lives — but with one persona per factor combination this is a
hypothesis for future work, not a finding.
"""
    wmd("p13-deep-dive.md", md)

    # ================================================== 3. interior census
    census = []
    for (pid, cell) in sorted(eps_a):
        g = adj.gate_cell(eps_a[(pid, cell)])
        if g["interior"]:
            census.append([pid, personas[pid], cell, 0.7, len(eps_a[(pid, cell)]),
                           g["k"], g["n"], round(g["mean"], 4),
                           round(g["cp95"][0], 4), round(g["cp95"][1], 4)])
    wcsv(os.path.join(FS, "pv-interior-census.csv"),
         ["personaId", "leaning", "cell", "temperature", "episodes", "k", "n",
          "meanRound1Coop", "cpLo", "cpHi"], census)
    ctbl = ["| persona | leaning | cell | rate | CP95 |", "|---|---|---|---|---|"]
    for r in census:
        ctbl.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[7]:.3f} "
                    f"| [{r[8]:.3f}, {r[9]:.3f}] |")
    md = f"""# Interior-cell census — the Branch-2 exhibit

{BANNER}
**What this is:** the corrected, complete list of every interior
persona-cell in the Phase 5 tier-A design (96 units, gpt, T=0.7).
Branch 2 hinges on *existence*; this is the existence exhibit.

**{len(census)}/96 units interior, concentrated in 6 of 16 personas**
(p13: 4 · p05: 3 · p15: 3 · p04: 2 · p07: 1 · p12: 1); ten personas are
pure-corner everywhere. 7 cooperative-leaning / 7 defect-leaning rows —
interiority is not a leaning phenomenon.

{chr(10).join(ctbl)}

CSV: `figure-sources/pv-interior-census.csv`. Gate: seat-level CP95 wholly
inside (0.05, 0.95) — the registered interior gate, unchanged.
"""
    wmd("interior-census.md", md)

    # ================================================== 4. P5-2 decomposition
    bcc = report["P5-2"]["byConflictCell"]
    rep_keys = [k for k in bcc if "rep-" in k]
    swap_keys = [k for k in bcc if "os-swap" in k]
    rk = sum(bcc[k]["k"] for k in rep_keys)
    rn = sum(bcc[k]["n"] for k in rep_keys)
    dtbl = ["| conflict subset | k/n | share | CP95 | verdict at pinned bounds |",
            "|---|---|---|---|---|"]
    for k in sorted(rep_keys) + sorted(swap_keys):
        v = bcc[k]
        dtbl.append(f"| {k} | {v['k']}/{v['n']} | {v['share']:.4f} | "
                    f"[{v['cp95'][0]:.3f}, {v['cp95'][1]:.3f}] | {v['verdict']} |")
    rv = adj.p52_verdict(rk, rn)
    lean_rows = []
    for lean in ("cooperative-leaning", "defect-leaning"):
        keys = [k for k in rep_keys if k.startswith(lean)]
        kk = sum(bcc[k]["k"] for k in keys)
        nn = sum(bcc[k]["n"] for k in keys)
        vv = adj.p52_verdict(kk, nn)
        lean_rows.append(f"| rep pooled, {lean} | {kk}/{nn} | {vv['share']:.4f} "
                         f"| [{vv['cp95'][0]:.3f}, {vv['cp95'][1]:.3f}] | "
                         f"{vv['verdict']} |")
    pooled = report["P5-2"]["pooled"]
    md = f"""# P5-2 decomposition — the clean persona-dominance claim

{BANNER}
**What this is:** the registered pooled P5-2 result (task-consistent share
{pooled['share']:.4f}, CP [{pooled['cp95'][0]:.3f}, {pooled['cp95'][1]:.3f}]
→ **persona-dominant**) broken into its unconfounded and confounded parts.
Coding is the operator-signed outcome-blind D2 ruling
(`docs/phase5-close/adjudication-decisions.json`); nothing recoded here.

## By conflict cell (registered cells, seat-level round 1)

{chr(10).join(dtbl)}

## The unconfounded subset: rep S2-conflict cells

Rep cells are payoff-opposed with **no word/role dissociation** — the
clean reading of persona-vs-task dominance:

| subset | k/n | share | CP95 | verdict at pinned bounds |
|---|---|---|---|---|
| rep pooled (4 cells) | {rk}/{rn} | {rv['share']:.4f} | [{rv['cp95'][0]:.3f}, {rv['cp95'][1]:.3f}] | {rv['verdict']} |
{chr(10).join(lean_rows)}

## Reading

- The **swap conflict cell** (defect-leaning|os-swap, 0/320) is the
  word-confounded component: task-consistent there = follow the DEFECT
  role = refuse the COOPERATE word, and personas never do — but that cell
  cannot separate persona-loyalty from word-following.
- The **rep subset** ({rk}/{rn} = {rv['share']:.3f}) is confound-free:
  personas follow their assigned leaning against the task-consistent
  play in ~{1 - rv['share']:.0%} of seats. CP upper bound
  {rv['cp95'][1]:.3f} {'≤' if rv['cp95'][1] <= adj.P52_UB else '>'} the
  pinned persona-dominant bound {adj.P52_UB} → the rep-only reading is
  **{rv['verdict']}** on its own (exploratory recomputation at the pinned
  bounds, not a registered verdict).
- Within rep cells the effect is leaning-asymmetric: defect-leaning
  personas are more persona-consistent than cooperative-leaning ones
  (see per-leaning rows).
"""
    wmd("p52-decomposition.md", md)

    # ================================================== 5. entropy anomaly
    # recompute per (T, lane, family) from runs directly
    groups = defaultdict(lambda: defaultdict(int))  # (T,lane,family)->action counts
    cellsets = defaultdict(set)
    for r in runs.values():
        a = arms.get(r["armId"])
        if a is None or not (r["completed"] and not r["invalid"] and r["round1"]):
            continue
        T = a["temperature"]
        lane = "bare" if a.get("personaId") is None else "persona"
        fam = adj.FAMILY_OF.get(a["cell"], a["cell"])
        for act in r["round1"]:
            groups[(T, lane, fam)][act] += 1
        cellsets[T].add((lane, a["cell"], a.get("personaId")))
    rows, pooled_T = [], defaultdict(lambda: defaultdict(int))
    for (T, lane, fam), cnts in sorted(groups.items()):
        n = sum(cnts.values())
        rows.append([T, lane, fam, n, round(adj.entropy(cnts), 4)])
        for k, v in cnts.items():
            pooled_T[T][k] += v
    wcsv(os.path.join(FS, "pv-entropy-decomposition.csv"),
         ["temperature", "lane", "family", "seats", "entropyBits"], rows)
    # matched-composition check: units present at ALL of 0.7/1.0/1.3
    allT = [0.7, 1.0, 1.3]
    matched = set.intersection(*(cellsets[t] for t in allT))
    m_ent = {}
    for T in allT:
        cnts = defaultdict(int)
        for r in runs.values():
            a = arms.get(r["armId"])
            if (a and a["temperature"] == T and r["completed"]
                    and not r["invalid"] and r["round1"]
                    and ("bare" if a.get("personaId") is None else "persona",
                         a["cell"], a.get("personaId")) in matched):
                for act in r["round1"]:
                    cnts[act] += 1
        m_ent[T] = (adj.entropy(cnts), sum(cnts.values()))
    pooled_ent = {T: adj.entropy(c) for T, c in pooled_T.items()}
    dtbl = ["| T | pooled entropy (all units at T) | seats | matched-unit entropy | seats |",
            "|---|---|---|---|---|"]
    for T in allT:
        n_all = sum(pooled_T[T].values())
        dtbl.append(f"| {T} | {pooled_ent[T]:.4f} | {n_all} | "
                    f"{m_ent[T][0]:.4f} | {m_ent[T][1]} |")
    ltbl = ["| T | lane | family | seats | entropy (bits) |", "|---|---|---|---|---|"]
    for T, lane, fam, n, e in rows:
        ltbl.append(f"| {T} | {lane} | {fam} | {n} | {e:.4f} |")
    surv = m_ent[1.3][0] < m_ent[0.7][0] and m_ent[1.0][0] < m_ent[0.7][0]
    md = f"""# The entropy-vs-T anomaly — artifact or effect?

{BANNER}
**What this is:** the registered P5-4 secondary showed round-1 choice
entropy *falling* with temperature (0.906 → 0.787 → 0.777 bits), the
opposite of the naive expectation. This decomposes it.

## How the entropy was computed (registered secondary)

Adjudicator (`phase5_closeout_adjudicate.py`): pooled round-1 action
counts across **every completed valid run at each T**, Shannon entropy
`-Σ p·log2 p` over the two actions. Crucially, the pooled T=0.7 count
includes the full 96-cell tier-A lattice (16 personas × 6 cells) plus all
T=0.7 sweep and sentinel lanes, while T∈{{1.0, 1.3}} contain **only** the
sweep subset (4 personas + bare, 3 cells). The pooled statistic compares
different unit mixes — a composition (Simpson-type) confound by
construction.

## Decomposition by lane × cell family

{chr(10).join(ltbl)}

## The composition test: matched units only

Restricting every T to the identical unit set (lane × cell × persona
present at all three temperatures — the sweep lattice):

{chr(10).join(dtbl)}

## Verdict on the anomaly

{"**The decline survives matched-unit decomposition**: on the identical unit set entropy still falls from T=0.7 to higher temperatures. Aggregation explains part of the pooled magnitude but not the direction — the anomaly is real at the sweep-lattice level and remains an open observation (mechanism scope-sealed to future work)."
 if surv else
 "**Artifact.** On the matched unit set the decline disappears or reverses; the pooled decline is a composition effect — T=0.7 mixes in the 96-cell lattice whose action distribution is nearer 50/50 than the sweep subset's. The pooled secondary is correctly computed but must not be read as a within-unit temperature effect."}

Numbers above are exact recomputations from the event store; CSV:
`figure-sources/pv-entropy-decomposition.csv`.
"""
    wmd("entropy-anomaly.md", md)

    # ================================================== INDEX
    md = f"""# Post-verdict analyses — INDEX

{BANNER}
Read order:

1. `clause-b-anatomy.md` — the swap-cell word/payoff confound, per-persona
   table, what the data cannot decide (de-confounding cell never run).
2. `p13-deep-dive.md` — the sole Family-E δ-slope pass: card, all cells,
   trajectories, trait gradient (exploratory).
3. `interior-census.md` — corrected full list of the {len(census)} interior
   persona-cells; the Branch-2 existence exhibit.
4. `p52-decomposition.md` — pooled 0.128 split into the unconfounded rep
   subset vs the word-confounded swap cell, per leaning.
5. `entropy-anomaly.md` — falling-entropy secondary decomposed by lane and
   family; matched-unit Simpson test.

Figure sources under `figure-sources/pv-*.csv`. All regenerable:
`cd artifacts/api-server && uv run --with numpy --with scipy python
engine/gen_post_verdict.py`.
"""
    wmd("INDEX.md", md)
    print("post-verdict pack complete")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
