#!/usr/bin/env python3
"""R2 items 4 + 5 — complete persona table and sample-hierarchy/estimand
table (DOCUMENTATION, zero subject calls; regenerable from the sealed
persona file and the recorded event store)."""
from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from phase5_closeout_adjudicate import (  # noqa: E402
    DB_PATH, load_runs, load_personas, load_p5_arms, collect)

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                    "..", "..", "..")
P5 = os.path.join(ROOT, "docs", "phase5")
OUT = os.path.join(ROOT, "docs", "analysis")


def persona_table() -> None:
    with open(os.path.join(P5, "personas-v4.json")) as f:
        doc = json.load(f)
    file_sha = hashlib.sha256(
        open(os.path.join(P5, "personas-v4.json"), "rb").read()).hexdigest()
    L = []
    a = L.append
    a("# Complete persona table — R2 item 4")
    a("")
    a("> **STATUS: DOCUMENTATION — R2, 2026-07-29. Zero subject calls. "
      "Generated by `engine/r2_gen_docs.py` from the sealed persona file "
      "`docs/phase5/personas-v4.json` "
      f"(sha256 `{file_sha}`, sealed in `docs/phase5/seal-record.md` and "
      "OTS-anchored via `docs/phase5-close/SHA256SUMS.txt` — all elements "
      "predate all Phase 5 data).**")
    a("")
    a("> **Header note.** The confirmatory unit is the **complete persona "
      "sentence** (the preamble below, verbatim). Names, ages, and "
      "occupations are **uncontrolled semantic treatments** — the "
      "banned-content guard excluded explicit game terminology and action "
      "recommendations, nothing more. Trait-level interpretations "
      "(attributing behavior to d1/d2/d3 factors) are **exploratory**.")
    a("")
    a(f"- generation rule: `{doc['compositionRule']}`")
    a(f"- leaning rule: `{doc['leaningRule']}`")
    a(f"- PRNG: `{doc['prng']}`, seed `{doc['seed']}` "
      f"(temperature-subset seed `{doc['subsetSeed']}`)")
    a(f"- banned-content guard: `{doc['bannedContentGuard']}`")
    a(f"- generated: {doc['generatedAt']}; sealed status: `{doc['status']}`")
    a("")
    a("| id | persona sentence (verbatim) | sha256 | name | age | "
      "occupation | traits (d1/d2/d3, ageBand) | leaning (score) |")
    a("|---|---|---|---|---|---|---|---|")
    for p in doc["personas"]:
        f_ = p["factors"]
        calc = hashlib.sha256(p["preamble"].encode()).hexdigest()
        flag = "" if calc == p["sha256"] else " **SHA MISMATCH**"
        a(f"| {p['id']} | {p['preamble']} | `{p['sha256'][:12]}…`{flag} | "
          f"{p['name']} | {p['age']} | {p['occupation']} | "
          f"{f_['d1']} / {f_['d2']} / {f_['d3']}, {f_['ageBand']} | "
          f"{p['leaning']} ({p['leaningScore']}) |")
    a("")
    a("Per-row sha256 values are recomputed from the verbatim sentence at "
      "generation time of this table; any mismatch would be flagged "
      "inline (none are).")
    with open(os.path.join(OUT, "persona-table.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote docs/analysis/persona-table.md")


def hierarchy() -> None:
    runs = load_runs()
    personas = load_personas()
    arms = load_p5_arms()
    col = collect(runs, personas)

    db = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    n_calls = db.execute(
        "SELECT COUNT(*) FROM events WHERE type='llm.requested'").fetchone()[0]
    n_rounds = db.execute(
        "SELECT COUNT(*) FROM events WHERE type='round.played'").fetchone()[0]
    p5_arm_ids = set(arms)
    p5_runs = [r for r in runs.values() if r["armId"] in p5_arm_ids]
    p5_valid = [r for r in p5_runs if r["completed"] and not r["invalid"]]
    cells = sorted({a["cell"] for a in arms.values() if a.get("cell")})
    pids = sorted(personas)
    tier_a_eps = sum(len(v) for v in col["epsA"].values())

    L = []
    a = L.append
    a("# Sample hierarchy and estimands — R2 item 5")
    a("")
    a("> **STATUS: DOCUMENTATION — R2, 2026-07-29. Zero subject calls. "
      "Generated by `engine/r2_gen_docs.py` from the recorded event "
      "store (read-only) and the sealed arms/personas files.**")
    a("")
    a("## Hierarchy (Phase 5, exact recorded counts)")
    a("")
    a("| level | definition | count |")
    a("|---|---|---|")
    a("| deployment | model × provider config (gpt-4.1 primary; the "
      "cross-vendor lane is descriptive-only) | 1 primary |")
    a(f"| persona prompt | sealed persona sentence prepended as system "
      f"prefix | {len(pids)} (+ bare = no prefix) |")
    a(f"| condition (cell) | game × δ × wording × swap surface | "
      f"{len(cells)} distinct cells; {len(arms)} arms "
      f"(cell × persona × temperature) |")
    a(f"| episode | one seeded game instance | {len(p5_valid)} valid "
      f"completed Phase 5 episodes ({len(p5_runs)} dispatched; tier-A "
      f"persona×cell series hold {tier_a_eps} episodes = 96 units × 6) |")
    a("| seat | one player position inside an episode | 2 per episode "
      "(both seats are the subject) |")
    a(f"| round | one simultaneous move pair | {n_rounds} round events "
      f"recorded (all phases in this store) |")
    a(f"| call | one LLM request | {n_calls} llm.requested events "
      f"recorded (all phases in this store) |")
    a("")
    a("## Statistical cluster per primary claim")
    a("")
    a("| claim | statistic | cluster (independence unit) |")
    a("|---|---|---|")
    a("| P5-1a interiority | CP interval on seat-level round-1 trials "
      "(k, n=2·episodes) | episode (seats within an episode share a "
      "transcript; seat-level counting is disclosed as anti-conservative "
      "if seats are positively dependent) |")
    a("| P5-1b SD vs human pins | between-persona SD of persona-cell "
      "means | persona (n=16 fixed prompts) |")
    a("| P5-2 conflict cells | CP bound on pooled round-1 choices | "
      "episode within conflict cell |")
    a("| P5-3 clause (a) | δ-slope of round-1 coop, gate + one-sided LB | "
      "episode within (persona, level, δ) cell; family audited in "
      "`r2/p13-family-audit.md` |")
    a("| P5-3 clause (b) | CP LB on refusal rate | episode (2 seats) "
      "within (persona, T) |")
    a("| P5-4 temperature | interiority flips across T on sweep units | "
      "unit = (persona, cell) at fixed T |")
    a("")
    a("## The two estimands")
    a("")
    a("1. **Conditional finite-panel estimand** — properties of *these "
      "16 fixed persona prompts* (and the bare subject), treated as a "
      "fixed panel. All registered Phase 5 predicates (P5-1a, P5-1b, "
      "P5-2, P5-3, P5-4) attach HERE: personas enter as fixed units, "
      "and no claim generalizes beyond the panel.")
    a("2. **Persona-population estimand** — properties of the "
      "trait-persona *generator* (the composition rule the 16 were "
      "drawn from), for which the panel is a sample of n=16 at the "
      "persona level. Only the exploratory layers (leaning splits, "
      "trait-gradient sketches, between/within decompositions read as "
      "generator properties) gesture at THIS estimand, and n=16 with "
      "3 binary factors leaves it weakly identified — every such "
      "reading is banner-labeled exploratory.")
    a("")
    a("Any sentence in the paper claiming 'persona pools do X' must "
      "state which estimand it attaches to; the registered record "
      "supports only the first.")
    with open(os.path.join(OUT, "hierarchy.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("wrote docs/analysis/hierarchy.md")


if __name__ == "__main__":
    persona_table()
    hierarchy()
