#!/usr/bin/env python3
"""Add the retained percentile-bootstrap gate to the final p13 audit.

The primary exact-episode family audit is generated by
``submission_gate_exact_cluster.py``. An earlier zero-call submission analysis
also evaluated the episode-cluster percentile-bootstrap gate. That construction
is not primary because percentile intervals become degenerate at exact corners,
but selective omission would violate the paper's reporting rule. This script
therefore publishes all three post-adjudication variants without changing any
sealed verdict.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "analysis" / "submission"
FIG = OUT / "figure-sources"
SUMMARY = OUT / "submission-analysis-summary.json"
FINAL_JSON = FIG / "p13-family-audit-final.json"
FINAL_MD = OUT / "p13-family-audit-final.md"


def fmt_candidates(rows: list[list[str]]) -> str:
    return ", ".join("/".join(x) for x in rows) or "none"


def table_row(label: str, rec: dict, b: int) -> str:
    slope = rec.get("observedTmaxRawSlope")
    if slope is None:
        return f"| {label} | — | none | none | — | — | — | — |"
    argmax = "/".join(rec.get("argmax") or [])
    ci = rec["mcClopperPearson95"]
    q95 = rec.get("finiteTmaxQuantiles", {}).get("q95", float("nan"))
    return (
        f"| {label} | {slope:+.4f} | {argmax} | "
        f"{fmt_candidates(rec.get('observedGatePassing', []))} | "
        f"{rec['exceedances']:,}/{b:,} | {rec['pAddOne']:.6f} | "
        f"[{ci[0]:.6f}, {ci[1]:.6f}] | {q95:.4f} |"
    )


def main() -> int:
    summary = json.loads(SUMMARY.read_text(encoding="utf-8"))
    final = json.loads(FINAL_JSON.read_text(encoding="utf-8"))

    bootstrap = summary["results"]["p13Family"][
        "episodeClusterBootstrapGate_rawSlopeMax"
    ]
    # Preserve the exact value and seed from the archived first-stage analysis.
    final["episodeClusterBootstrapGate_rawSlopeMax"] = bootstrap
    final["postAdjudicationStatus"] = {
        "registeredAtOriginalFreeze": False,
        "specifiedAfterExternalReview": True,
        "reportingRule": (
            "Report all computed gate variants. The exact-episode gate is primary "
            "because it remains non-degenerate at exact corners; no post hoc variant "
            "can create prospective confirmation."
        ),
        "bootstrapSourceSeed": summary["results"]["p13Family"].get("seed"),
    }
    FINAL_JSON.write_text(json.dumps(final, indent=2) + "\n", encoding="utf-8")

    b = int(final["permutations"])
    historical = final["historicalSeatGate_rawSlopeMax"]
    exact = final["episodeExactCPGate_rawSlopeMax"]

    lines = [
        "# Final high-precision P5-3(a) family audit",
        "",
        "> **STATUS: POST-ADJUDICATION SENSITIVITY — ZERO SUBJECT CALLS.** Historical mechanical verdicts are unchanged. No familywise gate was registered at the original freeze. After external review identified the multiplicity and dependence defects, the variants below were specified and executed against the archived databases with fixed seeds; generated outputs were committed regardless of direction.",
        "",
        "## Design and reporting rule",
        "",
        f"- Permutations: **{b:,}** for each construction.",
        "- Episode outcomes are permuted between δ=.90 and δ=.10 within each persona × wording candidate, preserving arm sizes.",
        "- Statistic: maximum raw difference in episode-mean round-one cooperation among candidates passing both condition gates.",
        "- Monte Carlo p-values use `(r+1)/(B+1)` with exact intervals for Monte Carlo uncertainty.",
        "- **Primary sensitivity:** the conservative exact-episode CP projection, because it treats the episode as the unit and does not collapse to zero uncertainty at exact corners.",
        "- **Retained sensitivity:** the episode-cluster percentile-bootstrap gate. It is reported because it was computed, but rejected as primary because percentile intervals become degenerate when every observed episode agrees.",
        "- These analyses were not sealed before computation and cannot retroactively create a prospectively family-controlled result. p13 remains a replication target under every numerical outcome.",
        "",
        "## Results",
        "",
        "| gate construction | observed max slope | argmax | passing candidates | exceedances / B | p | MC 95% interval | null 95th percentile |",
        "|---|---:|---|---|---:|---:|---|---:|",
        table_row("Historical seat-level CP gate", historical, b),
        table_row("Episode-cluster percentile-bootstrap gate (retained, non-primary)", bootstrap, b),
        table_row("Episode-exact CP projection (**primary sensitivity**)", exact, b),
        "",
        "The percentile-bootstrap construction is the only variant below 0.05 (`p=0.043455`, MC 95% `[0.042561, 0.044353]`). That result does not rescue the historical claim: the construction was selected after the inferential defect was found, its corner behavior is unsuitable for the assay's purpose, and no familywise procedure was registered at freeze. Under the primary exact-episode gate, p13 is excluded and the maximum surviving slope is +0.0833 with `p=0.773206`.",
        "",
        "## Status",
        "",
        "The archived data do not supply a prospectively controlled persona-level incentive-response existence result. The historical mechanical verdict remains visible; the scientific interpretation is a replication target plus an auditable example of where exact procedural enforcement stopped short of valid family-level inference.",
        "",
        "Machine-readable summary: `figure-sources/p13-family-audit-final.json`.",
    ]
    FINAL_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("augment_p13_audit_variants: reported historical, bootstrap, and exact variants")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
